In [8]:
from sklearn.preprocessing import LabelEncoder

In [1]:
import pandas as pd

claims = pd.read_csv("claims_preprocessed_v2.csv")

claims.head()

,Claim_Form_Type,Provider_Specialty,Payer,Place_of_Service_Code,Place_of_Service_Desc,Diagnosis_Code,Procedure_Code,Procedure_Desc,Modifier_Code,Billed_Amount,...,Provider_Payer_Prior_Denial_Count,Chronic_Condition_Flag,Claim_Status,CARC_Code,Denial_Reason,Service_Month,Submission_Month,Service_DayOfWeek,Submission_DayOfWeek,Claim_Submission_Delay
0,837P,Orthopedics,Medicare,23,Emergency Room,I10,29881,Knee arthroscopy/surgery,No_Modifier,3796.96,...,3,False,Approved,NaN,NaN,7,7,2,4,9
1,837I,Internal Medicine,Medicaid,21,Inpatient Hospital,J18.9,36415,Blood draw,76,27.95,...,1,False,Approved,NaN,NaN,5,5,3,3,7
2,837P,Radiology,Medicaid,11,Office,E78.5,99213,"Office visit, low complexity",No_Modifier,141.00,...,2,True,Approved,NaN,NaN,8,8,1,4,3
3,837I,Orthopedics,Aetna,22,Outpatient Hospital,M54.5,93000,EKG,No_Modifier,135.13,...,2,True,Denied,CO-45,Charge exceeds fee schedule/contracted amount,2,2,6,4,12
4,837I,Orthopedics,Medicare,21,Inpatient Hospital,K21.9,99213,"Office visit, low complexity",No_Modifier,180.85,...,2,False,Approved,NaN,NaN,3,3,1,2,8

In [2]:
claims.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Claim_Form_Type                    15000 non-null  str
 1   Provider_Specialty                 15000 non-null  str
 2   Payer                              15000 non-null  str
 3   Place_of_Service_Code              15000 non-null  int64
 4   Place_of_Service_Desc              15000 non-null  str
 5   Diagnosis_Code                     15000 non-null  str
 6   Procedure_Code                     15000 non-null  int64
 7   Procedure_Desc                     15000 non-null  str
 8   Modifier_Code                      15000 non-null  str
 9   Billed_Amount                      15000 non-null  float64
 10  Service_Date                       15000 non-null  str
 11  Claim_Submission_Date              15000 non-null  str
 12  Days_to_Submission                 15000 non-null  int64
 13  Payer_Timely_Filing_Limit_Days     15000 non-null  int64
 14  Prior_Auth_Required                15000 non-null  bool
 15  Prior_Auth_Obtained                15000 non-null  bool
 16  Eligibility_Verified               15000 non-null  bool
 17  Duplicate_Claim_Flag               15000 non-null  bool
 18  NCCI_Bundling_Flag                 15000 non-null  bool
 19  Clearinghouse_Validation_Passed    15000 non-null  bool
 20  Provider_Monthly_Claim_Volume      15000 non-null  int64
 21  Provider_Payer_Prior_Denial_Count  15000 non-null  int64
 22  Chronic_Condition_Flag             15000 non-null  bool
 23  Claim_Status                       15000 non-null  str
 24  CARC_Code                          2710 non-null   str
 25  Denial_Reason                      2710 non-null   str
 26  Service_Month                      15000 non-null  int64
 27  Submission_Month                   15000 non-null  int64
 28  Service_DayOfWeek                  15000 non-null  int64
 29  Submission_DayOfWeek               15000 non-null  int64
 30  Claim_Submission_Delay             15000 non-null  int64
dtypes: bool(7), float64(1), int64(11), str(12)
memory usage: 4.3 MB

In [3]:
categorical_columns = claims.select_dtypes(include="object").columns

categorical_columns

C:\Users\Saroon\AppData\Local\Temp\ipykernel_8976\4186878912.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = claims.select_dtypes(include="object").columns

Index(['Claim_Form_Type', 'Provider_Specialty', 'Payer',
       'Place_of_Service_Desc', 'Diagnosis_Code', 'Procedure_Desc',
       'Modifier_Code', 'Service_Date', 'Claim_Submission_Date',
       'Claim_Status', 'CARC_Code', 'Denial_Reason'],
      dtype='str')

In [4]:
claims[categorical_columns].nunique().sort_values()

Claim_Form_Type            2
Claim_Status               2
Place_of_Service_Desc      4
Modifier_Code              5
Payer                      7
Provider_Specialty         8
CARC_Code                  8
Denial_Reason              8
Procedure_Desc            10
Diagnosis_Code            12
Service_Date             700
Claim_Submission_Date    853
dtype: int64

In [5]:
claims[["Days_to_Submission", "Claim_Submission_Delay"]].head(10)

   Days_to_Submission  Claim_Submission_Delay
0                   9                       9
1                   7                       7
2                   3                       3
3                  12                      12
4                   8                       8
5                  17                      17
6                   8                       8
7                  23                      23
8                   5                       5
9                  38                      38

In [6]:
claims.drop(columns=["Days_to_Submission"], inplace=True)

In [7]:
claims.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 30 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Claim_Form_Type                    15000 non-null  str
 1   Provider_Specialty                 15000 non-null  str
 2   Payer                              15000 non-null  str
 3   Place_of_Service_Code              15000 non-null  int64
 4   Place_of_Service_Desc              15000 non-null  str
 5   Diagnosis_Code                     15000 non-null  str
 6   Procedure_Code                     15000 non-null  int64
 7   Procedure_Desc                     15000 non-null  str
 8   Modifier_Code                      15000 non-null  str
 9   Billed_Amount                      15000 non-null  float64
 10  Service_Date                       15000 non-null  str
 11  Claim_Submission_Date              15000 non-null  str
 12  Payer_Timely_Filing_Limit_Days     15000 non-null  int64
 13  Prior_Auth_Required                15000 non-null  bool
 14  Prior_Auth_Obtained                15000 non-null  bool
 15  Eligibility_Verified               15000 non-null  bool
 16  Duplicate_Claim_Flag               15000 non-null  bool
 17  NCCI_Bundling_Flag                 15000 non-null  bool
 18  Clearinghouse_Validation_Passed    15000 non-null  bool
 19  Provider_Monthly_Claim_Volume      15000 non-null  int64
 20  Provider_Payer_Prior_Denial_Count  15000 non-null  int64
 21  Chronic_Condition_Flag             15000 non-null  bool
 22  Claim_Status                       15000 non-null  str
 23  CARC_Code                          2710 non-null   str
 24  Denial_Reason                      2710 non-null   str
 25  Service_Month                      15000 non-null  int64
 26  Submission_Month                   15000 non-null  int64
 27  Service_DayOfWeek                  15000 non-null  int64
 28  Submission_DayOfWeek               15000 non-null  int64
 29  Claim_Submission_Delay             15000 non-null  int64
dtypes: bool(7), float64(1), int64(10), str(12)
memory usage: 4.2 MB

## Label Encoding

In [10]:
categorical_features = [
    "Claim_Form_Type",
    "Provider_Specialty",
    "Payer",
    "Diagnosis_Code",
    "Modifier_Code"
]
categorical_features

['Claim_Form_Type',
 'Provider_Specialty',
 'Payer',
 'Diagnosis_Code',
 'Modifier_Code']

In [11]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for column in categorical_features:
    le = LabelEncoder()
    claims[column] = le.fit_transform(claims[column])

    label_encoders[column] = le

In [12]:
claims[categorical_features].head()

   Claim_Form_Type  Provider_Specialty  Payer  Diagnosis_Code  Modifier_Code
0                1                   5      4               4              4
1                0                   3      3               7              2
2                1                   7      3               1              4
3                0                   5      0              10              4
4                0                   5      4               8              4

In [13]:
import joblib

joblib.dump(label_encoders, "label_encoders.pkl")

print("Label Encoders Saved Successfully!")

Label Encoders Saved Successfully!

In [14]:
claims.to_csv("claims_preprocessed_v3.csv", index=False)

print("Dataset Saved Successfully!")

Dataset Saved Successfully!